export default class ActionsTypes {
    static FETCHING = '_FETCHING'
    static ERROR = '_ERROR'
    static FETCHED = '_FETCHED'
    static RESET = '_RESET'

    //API
    static API_GET_COUNTRIES = "API_GET_COUNTRIES"

    //SEARCH TRAVELS
    static SEARCH_TRAVEL_RESET = "SEARCH_TRAVEL_RESET"
    static SEARCH_TRAVEL_CHANGE = "SEARCH_TRAVEL_CHANGE"
    static SEARCH_TRAVEL_CHANGE_PASSENGER = "SEARCH_TRAVEL_CHANGE_PASSENGER"
    static SEARCH_TRAVEL_CHANGE_FLIGHT = "SEARCH_TRAVEL_CHANGE_FLIGHT"
    static SEARCH_TRAVEL_ADD_FLIGHT = "SEARCH_TRAVEL_ADD_FLIGHT"
    static SEARCH_TRAVEL_REMOVE_FLIGHT = "SEARCH_TRAVEL_REMOVE_FLIGHT"
}
